// Code generated by protoc-gen-go.
// source: ientry.proto
// DO NOT EDIT!

package goatar

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type File struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Offset           *int64  `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Hash             []byte  `protobuf:"bytes,3,opt,name=hash" json:"hash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *File) Reset()         { *this = File{} }
func (this *File) String() string { return proto.CompactTextString(this) }
func (*File) ProtoMessage()       {}

func (this *File) GetPath() string {
	if this != nil && this.Path != nil {
		return *this.Path
	}
	return ""
}

func (this *File) GetOffset() int64 {
	if this != nil && this.Offset != nil {
		return *this.Offset
	}
	return 0
}

func (this *File) GetHash() []byte {
	if this != nil {
		return this.Hash
	}
	return nil
}

func init() {
}
